### ISSUE TITLE
confusing instructions referring to old git repo setup

### ISSUE THREAD

**Issue by natasha-aleksandrova** [UWPCE-PythonCert/ProgrammingInPython#44]
https://uwpce-pythoncert.github.io/PythonCertDevel/exercises/python_pushups.html

Put at least one solution in the lesson1 folder you created in git and submit it via pull request.

**Comment by natasha-aleksandrova** [comment]
![Uploading Screen Shot 2020-12-20 at 9.45.10 AM.png…]()

**Comment by natasha-aleksandrova** [comment]
repo needs to be audited for more instances ^^

**Comment by PythonCHB** [comment]
You seem to be looking at the old copy -- the current one is published in the github.io associated with this repo here:

https://uwpce-pythoncert.github.io/ProgrammingInPython/

Should we unpublish the old one to save confusion? or replace it with a link to this one?

Or is it still being used by not-quite finished self-paced version?

**Comment by natasha-aleksandrova** [comment]
It's still being used by previous self-paced version.

The issue was reported from new version of the course.. and I thought I was looking at the new site but now I can't find any instances. Let's just ignore this for now and I'll keep an eye on it if I get any more reports.

**Comment by PythonCHB** [comment]
Sounds good.

Let us know when everyone's done with the "old" version -- we should probably decommission it to prevent confusion.
