### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by natasha-aleksandrova** [UWPCE-PythonCert/ProgrammingInPython#59]
https://uwpce-pythoncert.github.io/ProgrammingInPython/modules/Modules.html#importing-from-packages

http://effbot.org/zone/import-confusion.htm

**Comment by PythonCHB** [comment]
Hmm -- that link says it "will return", but that's not very satisfactory :-(

I removed it for now -- if anyone can find another good reference that would be nice. I did some quick googling and didn't find anything I liked.

**Comment by PythonCHB** [comment]
NOTE: I don't think the auto-build system is working anymore -- we really need to get that fixed.

But I just rebuilt it by hand.

**Comment by natasha-aleksandrova** [comment]
thanks!
